### ISSUE TITLE
Improve/extend FastTables (not related to ProcessModel)

### ISSUE THREAD

**Issue by SamTh3D3v** [ThierryGoubier/ProcessModel#1]
Sorry Mr @ThierryGoubier, I did not know how else to contact you, so I posted here (as you suggested ;) ).
Since you are one of the contributors to pharo's FastTables and their usage, i would like to get your views/ideas about how to improve/extend them so they cover more widgets/features, thx :))

**Comment by ThierryGoubier** [comment]
I wasn't one of the contributor, I simply like the design very much and I experimented with the core code.

Hum, what could be nice on FastTable... I haven't looked at the code for a while, and I have some ideas about where it could go. First, your feelings, when you use it: is there something that strikes you?

**Comment by SamTh3D3v** [comment]
I am not an experimented pharo user, but i think that the fact that you can't manage cells (selecting/editing ..) is the main visible limitation, keyboard navigation also needs to be considered ...

**Comment by ThierryGoubier** [comment]
Editing cells is probably an issue of changing what is the kind of element (Morph) used inside the cell. The current ones don't support editing (and linking editing in the cell to the underlying model is not simple).

What do you mean about keyboard navigation? I do have some code (that is used in my derivative of FastTable) to do keyboard-based item selection (selection in a list by typing the beginning of the name; tab completes the name, typing appear as floating above the table).

**Comment by SamTh3D3v** [comment]
Indeed keyboard navigation works fine, my bad.
One more thing to consider is to support binding any kinds of widgets to a cell, ..
I did get some improvement ideas from Mr. Stephan Eggermout, in fact he is the one that suggested i contact you..
Someone in the community also suggested that i contact the ones in charge of the SPEC framework, since they are working on migrating some of their widgets to use FastTables, and they might be more aware of  the limitations that needed work ..

**Comment by ThierryGoubier** [comment]
Agreed.

Well, the FT base code supports any widget (I do have experiments integrating complete tabs from the GTInspector framework as rows inside the table). So what is needed?

Yes, the Spec people (Joan Fabry?) may have ideas.

**Comment by SamTh3D3v** [comment]
I am not quite sure yet what exactly is needed, i need to experiment more around that for a couple of days, and i will keep you posted so i can get your review/opinion if this is okay :)) 

And yes Johan Fabry is the one i've contacted.

**Comment by SamTh3D3v** [comment]
https://github.com/SamTheDev/Pharo-FastTable-improvements/issues :)
